### PR TITLE
Do not treat regular commits as failure

### LINKED ISSUE #9: Run fails with "No commit found for version: x.x.x"
I might be missing something but when a commit that is not a release is pushed, the run fails with:

> No commit found for version: x.x.x

This marks the repository's latest run as failed and I receive an email. That doesn't seem like an error to me, it's just a commit not to take into consideration.

Is there anything special to configure to silence those failures?

### PR DESCRIPTION
**Pull request by Zhouzi**
With this PR, regular commits are no more treated as a failure.

Fix #9

### CODE REVIEW

**Comment by Zhouzi** [comment]
Turns out GitHub dropped support for neutral exit codes :/ I realize this PR's changes are not ideal, feel free to ignore/close.

**Comment by pascalgn** [comment]
No, that's fine, I made similar changes to another action! Thanks for the PR! Could you possibly remove the line `// process.exitCode = 78;`, because I don't like commented code? Otherwise it looks good! 👍

**Comment by Zhouzi** [comment]
@pascalgn Sure, I just pushed the changes 👍

**Comment by pascalgn** [comment]
Thanks for the PR, it's merged now! 👍

**Pull request merged**
